/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedFieldRouteImport } from './routes/_authenticated/field'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedKontakterRouteImport } from './routes/_authenticated/kontakter'
import { Route as AuthenticatedKunderRouteImport } from './routes/_authenticated/kunder'
import { Route as AuthenticatedMissionRouteImport } from './routes/_authenticated/mission'
import { Route as AuthenticatedModulesRouteImport } from './routes/_authenticated/modules'
import { Route as AuthenticatedReviewRouteImport } from './routes/_authenticated/review'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as ApiLogoRouteImport } from './routes/api/logo'
import { Route as AuthUpdatePasswordRouteImport } from './routes/auth.update-password'
import { Route as AuthenticatedKontakterIndexRouteImport } from './routes/_authenticated/kontakter.index'
import { Route as AuthenticatedKontakterEntityIdRouteImport } from './routes/_authenticated/kontakter.$entityId'
import { Route as AuthenticatedKunderIndexRouteImport } from './routes/_authenticated/kunder.index'
import { Route as AuthenticatedKunderEntityIdRouteImport } from './routes/_authenticated/kunder.$entityId'
import { Route as ApiSsoExchangeRouteImport } from './routes/api/sso.exchange'
import { Route as AuthenticatedOOrgSlugIndexRouteImport } from './routes/_authenticated/o.$orgSlug.index'
import { Route as AuthenticatedOOrgSlugConnectionsRouteImport } from './routes/_authenticated/o.$orgSlug.connections'
import { Route as AuthenticatedOOrgSlugSettingsRouteImport } from './routes/_authenticated/o.$orgSlug.settings'
import { Route as AuthenticatedOOrgSlugSlackChannelsRouteImport } from './routes/_authenticated/o.$orgSlug.slack-channels'
import { Route as AuthenticatedOOrgSlugWWsSlugRouteImport } from './routes/_authenticated/o.$orgSlug.w.$wsSlug'
import { Route as AuthenticatedOOrgSlugWWsSlugIndexRouteImport } from './routes/_authenticated/o.$orgSlug.w.$wsSlug.index'
import { Route as AuthenticatedOOrgSlugWWsSlugModulesRouteImport } from './routes/_authenticated/o.$orgSlug.w.$wsSlug.modules'
import { Route as AuthenticatedOOrgSlugWWsSlugSettingsRouteImport } from './routes/_authenticated/o.$orgSlug.w.$wsSlug.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFieldRoute = AuthenticatedFieldRouteImport.update({
  id: '/field',
  path: '/field',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKontakterRoute = AuthenticatedKontakterRouteImport.update({
  id: '/kontakter',
  path: '/kontakter',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKunderRoute = AuthenticatedKunderRouteImport.update({
  id: '/kunder',
  path: '/kunder',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMissionRoute = AuthenticatedMissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModulesRoute = AuthenticatedModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewRoute = AuthenticatedReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiLogoRoute = ApiLogoRouteImport.update({
  id: '/api/logo',
  path: '/api/logo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUpdatePasswordRoute = AuthUpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedKontakterIndexRoute =
  AuthenticatedKontakterIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedKontakterRoute,
  } as any)
const AuthenticatedKontakterEntityIdRoute =
  AuthenticatedKontakterEntityIdRouteImport.update({
    id: '/$entityId',
    path: '/$entityId',
    getParentRoute: () => AuthenticatedKontakterRoute,
  } as any)
const AuthenticatedKunderIndexRoute =
  AuthenticatedKunderIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedKunderRoute,
  } as any)
const AuthenticatedKunderEntityIdRoute =
  AuthenticatedKunderEntityIdRouteImport.update({
    id: '/$entityId',
    path: '/$entityId',
    getParentRoute: () => AuthenticatedKunderRoute,
  } as any)
const ApiSsoExchangeRoute = ApiSsoExchangeRouteImport.update({
  id: '/api/sso/exchange',
  path: '/api/sso/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOOrgSlugIndexRoute =
  AuthenticatedOOrgSlugIndexRouteImport.update({
    id: '/o/$orgSlug/',
    path: '/o/$orgSlug/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOOrgSlugConnectionsRoute =
  AuthenticatedOOrgSlugConnectionsRouteImport.update({
    id: '/o/$orgSlug/connections',
    path: '/o/$orgSlug/connections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOOrgSlugSettingsRoute =
  AuthenticatedOOrgSlugSettingsRouteImport.update({
    id: '/o/$orgSlug/settings',
    path: '/o/$orgSlug/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOOrgSlugSlackChannelsRoute =
  AuthenticatedOOrgSlugSlackChannelsRouteImport.update({
    id: '/o/$orgSlug/slack-channels',
    path: '/o/$orgSlug/slack-channels',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOOrgSlugWWsSlugRoute =
  AuthenticatedOOrgSlugWWsSlugRouteImport.update({
    id: '/o/$orgSlug/w/$wsSlug',
    path: '/o/$orgSlug/w/$wsSlug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOOrgSlugWWsSlugIndexRoute =
  AuthenticatedOOrgSlugWWsSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOOrgSlugWWsSlugRoute,
  } as any)
const AuthenticatedOOrgSlugWWsSlugModulesRoute =
  AuthenticatedOOrgSlugWWsSlugModulesRouteImport.update({
    id: '/modules',
    path: '/modules',
    getParentRoute: () => AuthenticatedOOrgSlugWWsSlugRoute,
  } as any)
const AuthenticatedOOrgSlugWWsSlugSettingsRoute =
  AuthenticatedOOrgSlugWWsSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedOOrgSlugWWsSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/app': typeof AuthenticatedAppRoute
  '/field': typeof AuthenticatedFieldRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/kontakter': typeof AuthenticatedKontakterRouteWithChildren
  '/kunder': typeof AuthenticatedKunderRouteWithChildren
  '/mission': typeof AuthenticatedMissionRoute
  '/modules': typeof AuthenticatedModulesRoute
  '/review': typeof AuthenticatedReviewRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/logo': typeof ApiLogoRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/kontakter/$entityId': typeof AuthenticatedKontakterEntityIdRoute
  '/kunder/$entityId': typeof AuthenticatedKunderEntityIdRoute
  '/api/sso/exchange': typeof ApiSsoExchangeRoute
  '/kontakter/': typeof AuthenticatedKontakterIndexRoute
  '/kunder/': typeof AuthenticatedKunderIndexRoute
  '/o/$orgSlug/connections': typeof AuthenticatedOOrgSlugConnectionsRoute
  '/o/$orgSlug/settings': typeof AuthenticatedOOrgSlugSettingsRoute
  '/o/$orgSlug/slack-channels': typeof AuthenticatedOOrgSlugSlackChannelsRoute
  '/o/$orgSlug/': typeof AuthenticatedOOrgSlugIndexRoute
  '/o/$orgSlug/w/$wsSlug': typeof AuthenticatedOOrgSlugWWsSlugRouteWithChildren
  '/o/$orgSlug/w/$wsSlug/modules': typeof AuthenticatedOOrgSlugWWsSlugModulesRoute
  '/o/$orgSlug/w/$wsSlug/settings': typeof AuthenticatedOOrgSlugWWsSlugSettingsRoute
  '/o/$orgSlug/w/$wsSlug/': typeof AuthenticatedOOrgSlugWWsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/app': typeof AuthenticatedAppRoute
  '/field': typeof AuthenticatedFieldRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/mission': typeof AuthenticatedMissionRoute
  '/modules': typeof AuthenticatedModulesRoute
  '/review': typeof AuthenticatedReviewRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/logo': typeof ApiLogoRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/kontakter/$entityId': typeof AuthenticatedKontakterEntityIdRoute
  '/kunder/$entityId': typeof AuthenticatedKunderEntityIdRoute
  '/api/sso/exchange': typeof ApiSsoExchangeRoute
  '/kontakter': typeof AuthenticatedKontakterIndexRoute
  '/kunder': typeof AuthenticatedKunderIndexRoute
  '/o/$orgSlug/connections': typeof AuthenticatedOOrgSlugConnectionsRoute
  '/o/$orgSlug/settings': typeof AuthenticatedOOrgSlugSettingsRoute
  '/o/$orgSlug/slack-channels': typeof AuthenticatedOOrgSlugSlackChannelsRoute
  '/o/$orgSlug': typeof AuthenticatedOOrgSlugIndexRoute
  '/o/$orgSlug/w/$wsSlug/modules': typeof AuthenticatedOOrgSlugWWsSlugModulesRoute
  '/o/$orgSlug/w/$wsSlug/settings': typeof AuthenticatedOOrgSlugWWsSlugSettingsRoute
  '/o/$orgSlug/w/$wsSlug': typeof AuthenticatedOOrgSlugWWsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/field': typeof AuthenticatedFieldRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/kontakter': typeof AuthenticatedKontakterRouteWithChildren
  '/_authenticated/kunder': typeof AuthenticatedKunderRouteWithChildren
  '/_authenticated/mission': typeof AuthenticatedMissionRoute
  '/_authenticated/modules': typeof AuthenticatedModulesRoute
  '/_authenticated/review': typeof AuthenticatedReviewRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/logo': typeof ApiLogoRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/_authenticated/kontakter/$entityId': typeof AuthenticatedKontakterEntityIdRoute
  '/_authenticated/kunder/$entityId': typeof AuthenticatedKunderEntityIdRoute
  '/api/sso/exchange': typeof ApiSsoExchangeRoute
  '/_authenticated/kontakter/': typeof AuthenticatedKontakterIndexRoute
  '/_authenticated/kunder/': typeof AuthenticatedKunderIndexRoute
  '/_authenticated/o/$orgSlug/connections': typeof AuthenticatedOOrgSlugConnectionsRoute
  '/_authenticated/o/$orgSlug/settings': typeof AuthenticatedOOrgSlugSettingsRoute
  '/_authenticated/o/$orgSlug/slack-channels': typeof AuthenticatedOOrgSlugSlackChannelsRoute
  '/_authenticated/o/$orgSlug/': typeof AuthenticatedOOrgSlugIndexRoute
  '/_authenticated/o/$orgSlug/w/$wsSlug': typeof AuthenticatedOOrgSlugWWsSlugRouteWithChildren
  '/_authenticated/o/$orgSlug/w/$wsSlug/modules': typeof AuthenticatedOOrgSlugWWsSlugModulesRoute
  '/_authenticated/o/$orgSlug/w/$wsSlug/settings': typeof AuthenticatedOOrgSlugWWsSlugSettingsRoute
  '/_authenticated/o/$orgSlug/w/$wsSlug/': typeof AuthenticatedOOrgSlugWWsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/field'
    | '/knowledge'
    | '/kontakter'
    | '/kunder'
    | '/mission'
    | '/modules'
    | '/review'
    | '/settings'
    | '/api/logo'
    | '/auth/update-password'
    | '/kontakter/$entityId'
    | '/kunder/$entityId'
    | '/api/sso/exchange'
    | '/kontakter/'
    | '/kunder/'
    | '/o/$orgSlug/connections'
    | '/o/$orgSlug/settings'
    | '/o/$orgSlug/slack-channels'
    | '/o/$orgSlug/'
    | '/o/$orgSlug/w/$wsSlug'
    | '/o/$orgSlug/w/$wsSlug/modules'
    | '/o/$orgSlug/w/$wsSlug/settings'
    | '/o/$orgSlug/w/$wsSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app'
    | '/field'
    | '/knowledge'
    | '/mission'
    | '/modules'
    | '/review'
    | '/settings'
    | '/api/logo'
    | '/auth/update-password'
    | '/kontakter/$entityId'
    | '/kunder/$entityId'
    | '/api/sso/exchange'
    | '/kontakter'
    | '/kunder'
    | '/o/$orgSlug/connections'
    | '/o/$orgSlug/settings'
    | '/o/$orgSlug/slack-channels'
    | '/o/$orgSlug'
    | '/o/$orgSlug/w/$wsSlug/modules'
    | '/o/$orgSlug/w/$wsSlug/settings'
    | '/o/$orgSlug/w/$wsSlug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/field'
    | '/_authenticated/knowledge'
    | '/_authenticated/kontakter'
    | '/_authenticated/kunder'
    | '/_authenticated/mission'
    | '/_authenticated/modules'
    | '/_authenticated/review'
    | '/_authenticated/settings'
    | '/api/logo'
    | '/auth/update-password'
    | '/_authenticated/kontakter/$entityId'
    | '/_authenticated/kunder/$entityId'
    | '/api/sso/exchange'
    | '/_authenticated/kontakter/'
    | '/_authenticated/kunder/'
    | '/_authenticated/o/$orgSlug/connections'
    | '/_authenticated/o/$orgSlug/settings'
    | '/_authenticated/o/$orgSlug/slack-channels'
    | '/_authenticated/o/$orgSlug/'
    | '/_authenticated/o/$orgSlug/w/$wsSlug'
    | '/_authenticated/o/$orgSlug/w/$wsSlug/modules'
    | '/_authenticated/o/$orgSlug/w/$wsSlug/settings'
    | '/_authenticated/o/$orgSlug/w/$wsSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiLogoRoute: typeof ApiLogoRoute
  ApiSsoExchangeRoute: typeof ApiSsoExchangeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/field': {
      id: '/_authenticated/field'
      path: '/field'
      fullPath: '/field'
      preLoaderRoute: typeof AuthenticatedFieldRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kontakter': {
      id: '/_authenticated/kontakter'
      path: '/kontakter'
      fullPath: '/kontakter'
      preLoaderRoute: typeof AuthenticatedKontakterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kunder': {
      id: '/_authenticated/kunder'
      path: '/kunder'
      fullPath: '/kunder'
      preLoaderRoute: typeof AuthenticatedKunderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mission': {
      id: '/_authenticated/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof AuthenticatedMissionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modules': {
      id: '/_authenticated/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof AuthenticatedModulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/review': {
      id: '/_authenticated/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AuthenticatedReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/logo': {
      id: '/api/logo'
      path: '/api/logo'
      fullPath: '/api/logo'
      preLoaderRoute: typeof ApiLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/update-password': {
      id: '/auth/update-password'
      path: '/update-password'
      fullPath: '/auth/update-password'
      preLoaderRoute: typeof AuthUpdatePasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/kontakter/': {
      id: '/_authenticated/kontakter/'
      path: '/'
      fullPath: '/kontakter/'
      preLoaderRoute: typeof AuthenticatedKontakterIndexRouteImport
      parentRoute: typeof AuthenticatedKontakterRoute
    }
    '/_authenticated/kontakter/$entityId': {
      id: '/_authenticated/kontakter/$entityId'
      path: '/$entityId'
      fullPath: '/kontakter/$entityId'
      preLoaderRoute: typeof AuthenticatedKontakterEntityIdRouteImport
      parentRoute: typeof AuthenticatedKontakterRoute
    }
    '/_authenticated/kunder/': {
      id: '/_authenticated/kunder/'
      path: '/'
      fullPath: '/kunder/'
      preLoaderRoute: typeof AuthenticatedKunderIndexRouteImport
      parentRoute: typeof AuthenticatedKunderRoute
    }
    '/_authenticated/kunder/$entityId': {
      id: '/_authenticated/kunder/$entityId'
      path: '/$entityId'
      fullPath: '/kunder/$entityId'
      preLoaderRoute: typeof AuthenticatedKunderEntityIdRouteImport
      parentRoute: typeof AuthenticatedKunderRoute
    }
    '/api/sso/exchange': {
      id: '/api/sso/exchange'
      path: '/api/sso/exchange'
      fullPath: '/api/sso/exchange'
      preLoaderRoute: typeof ApiSsoExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/o/$orgSlug/': {
      id: '/_authenticated/o/$orgSlug/'
      path: '/o/$orgSlug'
      fullPath: '/o/$orgSlug/'
      preLoaderRoute: typeof AuthenticatedOOrgSlugIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/o/$orgSlug/connections': {
      id: '/_authenticated/o/$orgSlug/connections'
      path: '/o/$orgSlug/connections'
      fullPath: '/o/$orgSlug/connections'
      preLoaderRoute: typeof AuthenticatedOOrgSlugConnectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/o/$orgSlug/settings': {
      id: '/_authenticated/o/$orgSlug/settings'
      path: '/o/$orgSlug/settings'
      fullPath: '/o/$orgSlug/settings'
      preLoaderRoute: typeof AuthenticatedOOrgSlugSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/o/$orgSlug/slack-channels': {
      id: '/_authenticated/o/$orgSlug/slack-channels'
      path: '/o/$orgSlug/slack-channels'
      fullPath: '/o/$orgSlug/slack-channels'
      preLoaderRoute: typeof AuthenticatedOOrgSlugSlackChannelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/o/$orgSlug/w/$wsSlug': {
      id: '/_authenticated/o/$orgSlug/w/$wsSlug'
      path: '/o/$orgSlug/w/$wsSlug'
      fullPath: '/o/$orgSlug/w/$wsSlug'
      preLoaderRoute: typeof AuthenticatedOOrgSlugWWsSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/o/$orgSlug/w/$wsSlug/': {
      id: '/_authenticated/o/$orgSlug/w/$wsSlug/'
      path: '/'
      fullPath: '/o/$orgSlug/w/$wsSlug/'
      preLoaderRoute: typeof AuthenticatedOOrgSlugWWsSlugIndexRouteImport
      parentRoute: typeof AuthenticatedOOrgSlugWWsSlugRoute
    }
    '/_authenticated/o/$orgSlug/w/$wsSlug/modules': {
      id: '/_authenticated/o/$orgSlug/w/$wsSlug/modules'
      path: '/modules'
      fullPath: '/o/$orgSlug/w/$wsSlug/modules'
      preLoaderRoute: typeof AuthenticatedOOrgSlugWWsSlugModulesRouteImport
      parentRoute: typeof AuthenticatedOOrgSlugWWsSlugRoute
    }
    '/_authenticated/o/$orgSlug/w/$wsSlug/settings': {
      id: '/_authenticated/o/$orgSlug/w/$wsSlug/settings'
      path: '/settings'
      fullPath: '/o/$orgSlug/w/$wsSlug/settings'
      preLoaderRoute: typeof AuthenticatedOOrgSlugWWsSlugSettingsRouteImport
      parentRoute: typeof AuthenticatedOOrgSlugWWsSlugRoute
    }
  }
}

interface AuthenticatedKontakterRouteChildren {
  AuthenticatedKontakterEntityIdRoute: typeof AuthenticatedKontakterEntityIdRoute
  AuthenticatedKontakterIndexRoute: typeof AuthenticatedKontakterIndexRoute
}

const AuthenticatedKontakterRouteChildren: AuthenticatedKontakterRouteChildren =
  {
    AuthenticatedKontakterEntityIdRoute: AuthenticatedKontakterEntityIdRoute,
    AuthenticatedKontakterIndexRoute: AuthenticatedKontakterIndexRoute,
  }

const AuthenticatedKontakterRouteWithChildren =
  AuthenticatedKontakterRoute._addFileChildren(
    AuthenticatedKontakterRouteChildren,
  )

interface AuthenticatedKunderRouteChildren {
  AuthenticatedKunderEntityIdRoute: typeof AuthenticatedKunderEntityIdRoute
  AuthenticatedKunderIndexRoute: typeof AuthenticatedKunderIndexRoute
}

const AuthenticatedKunderRouteChildren: AuthenticatedKunderRouteChildren = {
  AuthenticatedKunderEntityIdRoute: AuthenticatedKunderEntityIdRoute,
  AuthenticatedKunderIndexRoute: AuthenticatedKunderIndexRoute,
}

const AuthenticatedKunderRouteWithChildren =
  AuthenticatedKunderRoute._addFileChildren(AuthenticatedKunderRouteChildren)

interface AuthenticatedOOrgSlugWWsSlugRouteChildren {
  AuthenticatedOOrgSlugWWsSlugModulesRoute: typeof AuthenticatedOOrgSlugWWsSlugModulesRoute
  AuthenticatedOOrgSlugWWsSlugSettingsRoute: typeof AuthenticatedOOrgSlugWWsSlugSettingsRoute
  AuthenticatedOOrgSlugWWsSlugIndexRoute: typeof AuthenticatedOOrgSlugWWsSlugIndexRoute
}

const AuthenticatedOOrgSlugWWsSlugRouteChildren: AuthenticatedOOrgSlugWWsSlugRouteChildren =
  {
    AuthenticatedOOrgSlugWWsSlugModulesRoute:
      AuthenticatedOOrgSlugWWsSlugModulesRoute,
    AuthenticatedOOrgSlugWWsSlugSettingsRoute:
      AuthenticatedOOrgSlugWWsSlugSettingsRoute,
    AuthenticatedOOrgSlugWWsSlugIndexRoute:
      AuthenticatedOOrgSlugWWsSlugIndexRoute,
  }

const AuthenticatedOOrgSlugWWsSlugRouteWithChildren =
  AuthenticatedOOrgSlugWWsSlugRoute._addFileChildren(
    AuthenticatedOOrgSlugWWsSlugRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedFieldRoute: typeof AuthenticatedFieldRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedKontakterRoute: typeof AuthenticatedKontakterRouteWithChildren
  AuthenticatedKunderRoute: typeof AuthenticatedKunderRouteWithChildren
  AuthenticatedMissionRoute: typeof AuthenticatedMissionRoute
  AuthenticatedModulesRoute: typeof AuthenticatedModulesRoute
  AuthenticatedReviewRoute: typeof AuthenticatedReviewRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedOOrgSlugConnectionsRoute: typeof AuthenticatedOOrgSlugConnectionsRoute
  AuthenticatedOOrgSlugSettingsRoute: typeof AuthenticatedOOrgSlugSettingsRoute
  AuthenticatedOOrgSlugSlackChannelsRoute: typeof AuthenticatedOOrgSlugSlackChannelsRoute
  AuthenticatedOOrgSlugIndexRoute: typeof AuthenticatedOOrgSlugIndexRoute
  AuthenticatedOOrgSlugWWsSlugRoute: typeof AuthenticatedOOrgSlugWWsSlugRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedFieldRoute: AuthenticatedFieldRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedKontakterRoute: AuthenticatedKontakterRouteWithChildren,
  AuthenticatedKunderRoute: AuthenticatedKunderRouteWithChildren,
  AuthenticatedMissionRoute: AuthenticatedMissionRoute,
  AuthenticatedModulesRoute: AuthenticatedModulesRoute,
  AuthenticatedReviewRoute: AuthenticatedReviewRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedOOrgSlugConnectionsRoute: AuthenticatedOOrgSlugConnectionsRoute,
  AuthenticatedOOrgSlugSettingsRoute: AuthenticatedOOrgSlugSettingsRoute,
  AuthenticatedOOrgSlugSlackChannelsRoute:
    AuthenticatedOOrgSlugSlackChannelsRoute,
  AuthenticatedOOrgSlugIndexRoute: AuthenticatedOOrgSlugIndexRoute,
  AuthenticatedOOrgSlugWWsSlugRoute:
    AuthenticatedOOrgSlugWWsSlugRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthUpdatePasswordRoute: typeof AuthUpdatePasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthUpdatePasswordRoute: AuthUpdatePasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiLogoRoute: ApiLogoRoute,
  ApiSsoExchangeRoute: ApiSsoExchangeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
